version:
  name: velociraptor
  version: 0.7.0
  commit: ac56954
  build_time: "2023-08-28T01:49:41Z"
  ci_build_url: https://github.com/Velocidex/velociraptor/actions/runs/5994623416
  compiler: go1.21.0
Client:
  server_urls:
  - https://velociraptor.foodcity.com:8000/
  ca_certificate: |
    -----BEGIN CERTIFICATE-----
    MIIDSzCCAjOgAwIBAgIQemM4VMN3UJdkvOlqRNh1yDANBgkqhkiG9w0BAQsFADAa
    MRgwFgYDVQQKEw9WZWxvY2lyYXB0b3IgQ0EwHhcNMjMwOTA1MTcyODAzWhcNMzMw
    OTAyMTcyODAzWjAaMRgwFgYDVQQKEw9WZWxvY2lyYXB0b3IgQ0EwggEiMA0GCSqG
    SIb3DQEBAQUAA4IBDwAwggEKAoIBAQCackB151280r4cZjFp5NfsDTkyUM51OnEn
    CJK3UE1FFZI+CoxoG7UiDcrrOLUt8Jqk1iPkKyHCer70JiJmhOv/7FsMOF4i4i5k
    uDth+kmBk2VVlGExzcjrTsMG/2BymhecSnL2Los9W1YkYyoR3oyV9Nhtrv3RVN8N
    3bjPNDK96nwcR0rEvws53mo2S9d0FKRvUyoakzD2j1b1Nfm+iXa2fLMJpuPZ+fhK
    RI+XPgABkUquV3QPToPMwOQAy0dadTlaApcI3mu+H4CHwWXeZ6pUTWXMFX9wPcCq
    4h8qWInmvqu93zRFsQ8br/gvBH34ai4guywInTM7oV9oorwNAj71AgMBAAGjgYww
    gYkwDgYDVR0PAQH/BAQDAgKkMB0GA1UdJQQWMBQGCCsGAQUFBwMBBggrBgEFBQcD
    AjAPBgNVHRMBAf8EBTADAQH/MB0GA1UdDgQWBBQsbRbwO2BRRGhGi5gNxVkzJcCn
    fjAoBgNVHREEITAfgh1WZWxvY2lyYXB0b3JfY2EudmVsb2NpZGV4LmNvbTANBgkq
    hkiG9w0BAQsFAAOCAQEAKhXWZ3WvyqYsvKRkYNQhgkhs5xo5lNXu/6bOdnZWldvX
    uIemmsbl2WHqi/BIWq4cazIxlAWHYGILIa9IrMxmA6zE81RpI8WpRLl690CKbIlT
    QHCe13KaD4H064BNquRiKzdoyA+LinPHMvSKHY/7W2Jhn2V5UfLK1IXjtmAc8uFx
    otz0jCvBxB4MY09ouhTBpgnfs9bQvCEMgeVBiVOvngB61VbhezSzIrleMoIPtDGf
    OUxNC4ZCTZbvyKYRnud/24zoH3+Pl+oaGoGNni+hvu5vVc9bFJnxA0ZY1yBy2zcr
    H5AEJcMNrBOYgl4VSw4ROE8doq5bZ/p9cE0O1oL1gA==
    -----END CERTIFICATE-----
  nonce: v45BDBGI/bA=
  writeback_darwin: /etc/velociraptor.writeback.yaml
  writeback_linux: /etc/velociraptor.writeback.yaml
  writeback_windows: $ProgramFiles\Velociraptor\velociraptor.writeback.yaml
  tempdir_windows: $ProgramFiles\Velociraptor\Tools
  max_poll: 60
  nanny_max_connection_delay: 600
  windows_installer:
    service_name: Velociraptor
    install_path: $ProgramFiles\Velociraptor\Velociraptor.exe
    service_description: Velociraptor service
  darwin_installer:
    service_name: com.velocidex.velociraptor
    install_path: /usr/local/sbin/velociraptor
  version:
    name: velociraptor
    version: 0.7.0
    commit: ac56954
    build_time: "2023-08-28T01:49:41Z"
    ci_build_url: https://github.com/Velocidex/velociraptor/actions/runs/5994623416
    compiler: go1.21.0
  use_self_signed_ssl: true
  pinned_server_name: VelociraptorServer
  max_upload_size: 5242880
  local_buffer:
    memory_size: 52428800
    disk_size: 1073741824
    filename_linux: /var/tmp/Velociraptor_Buffer.bin
    filename_windows: $TEMP/Velociraptor_Buffer.bin
    filename_darwin: /var/tmp/Velociraptor_Buffer.bin
